theme: jekyll-theme-leap-day
encoding: UTF-8
title: [Desarrollo de aplicaciones web]
email: tecnologia@sergiosoriano.es
description: [Apuntes del curso IFCD0210]
github_username: SorianoTech
author: Sergio Soriano
